// <auto-generated />
using Interviewssss.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Interviewssss.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230105170824_dbcon")]
    partial class dbcon
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DATA.Model.SuhbatOluvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Darajasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Loyxasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tajribasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Yunalish")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("suhbatOluvchis");
                });

            modelBuilder.Entity("DATA.Model.SuhbatTopshiruvchi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Daraja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OluvchiId")
                        .HasColumnType("integer");

                    b.Property<string>("Tajriba")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OluvchiId");

                    b.ToTable("topshiruvchi");
                });

            modelBuilder.Entity("DATA.Model.SuhbatTopshiruvchi", b =>
                {
                    b.HasOne("DATA.Model.SuhbatOluvchi", "suhbatOluvchi")
                        .WithMany("suhbatTopshiruvchis")
                        .HasForeignKey("OluvchiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("suhbatOluvchi");
                });

            modelBuilder.Entity("DATA.Model.SuhbatOluvchi", b =>
                {
                    b.Navigation("suhbatTopshiruvchis");
                });
#pragma warning restore 612, 618
        }
    }
}
